apiVersion: v1
kind: Pod
metadata:
  name: secure-hostpath-pod
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: host-log
          mountPath: /var/log
  volumes:
    - name: host-log
      emptyDir: {}